on: [pull_request]

jobs:
  build:
    env:
      FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
    strategy:
      matrix:
        os: [macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.6.x
      - run: yarn install --network-timeout 300000
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test
      - run: yarn package